.idea/.gitignore

Feat : .gitignore 파일 추가

---

build.gradle
src/main/java/com/donkeys_today/server/presentation/user/UserController.java
src/test/java/com/donkeys_today/server/docs/RestDocsSupport.java
src/test/java/com/donkeys_today/server/docs/user/UserControllerDocsTest.java

- close #3 
RestAssuredMockMVC dependency 추가 & 테스트 코드 작성 방식 RestAssured BDD style 로 변경

Feat : 테스트 의존성을 추가합니다. 

---

.gitignore
build.gradle
src/main/java/com/donkeys_today/server/auth/config/CorsMvcConfig.java
src/main/java/com/donkeys_today/server/auth/config/SecurityConfig.java
src/main/java/com/donkeys_today/server/auth/config/WhiteListConstants.java

- close #7 
기본적인 Spring Seuciry Chain을 세팅했습니다.
프론트엔드 배포 도메인에 따라 CorsMvcConfig와 Security의 Cors 도메인 수정이 필요할 것 같습니다.

Feat: Spring Security Chain 을 설정합니다.

---

.gitignore
Dockerfile
build.gradle
docker-compose.yml

- #13 
docker compose 를 이용한 무중단 배포 (Blue - Green Sterategy) 
궁금하신 부분은 질문 부탁드립니다 !

Feat : docker-compose 를 이용한 무중단 배포 구현

---

src/main/java/com/donkeys_today/server/domain/alarm/Alarm.java
src/main/java/com/donkeys_today/server/domain/alarm/AlarmRepository.java
src/main/java/com/donkeys_today/server/domain/diary/Diary.java
src/main/java/com/donkeys_today/server/domain/diary/DiaryRepository.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/domain/reply/ReplyRepository.java
src/main/java/com/donkeys_today/server/domain/user/ProviderType.java
src/main/java/com/donkeys_today/server/domain/user/RoleType.java
src/main/java/com/donkeys_today/server/domain/user/User.java

- close #24 
아래의 ERD 에 따라 Entity를 생성했습니다.

Feat: Entity를 생성합니다.

---

src/main/java/com/donkeys_today/server/application/user/UserService.java
src/main/java/com/donkeys_today/server/presentation/api/UserController.java
src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserInfoResponse.java

Feat: 프로필 조회 API 구현

---

src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
src/main/java/com/donkeys_today/server/application/diary/DiaryRetriever.java
src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java
src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
src/main/java/com/donkeys_today/server/presentation/user/dto/response/DiaryCreatedTimeGetResponse.java

- close #66 
Feat: 일기 작성 시간 조회 API 구현

Feat: 일기 작성 시간 조회 API 구현

---

src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java

- close #70 
Fix: access token 을 이용한 로그인 방식으로 수정

Fix: access token 을 이용한 로그인 방식으로 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
src/main/java/com/donkeys_today/server/presentation/api/DiaryController.java

Bug: 충돌 해결

---

src/main/java/com/donkeys_today/server/application/user/UserService.java
src/main/java/com/donkeys_today/server/presentation/api/UserController.java
src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java

- close #82 
Refactor: 리프레시 토큰은 헤더로 받습니다.

Refactor: 리프레시 토큰은 헤더로 받습니다.

---

src/main/java/com/donkeys_today/server/application/user/UserRemover.java
src/main/java/com/donkeys_today/server/application/user/UserService.java
src/main/java/com/donkeys_today/server/domain/alarm/Alarm.java
src/main/java/com/donkeys_today/server/domain/diary/Diary.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/presentation/api/UserController.java
src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
src/main/java/com/donkeys_today/server/presentation/user/dto/response/UserDeleteResponse.java

- close #84 
Feat: 데모데이용 회원탈퇴 기능 구현

Feat: 데모데이용 회원탈퇴 기능 구현

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/application/reply/ReplyCreator.java
src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCreatedResponse.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/ReplyType.java
src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java

- close #86 
일기 작성의 경우 세가지 타입이 존재합니다. 
그날 지운 데이터가 있을 경우 - No Reply
욕설이 포함된 일기가 있을 경우 - Static Reply
일반 일기 - Dynamic Reply 
세 가지 케이스가 존재하기 때문에, 일기 작성시 반환 타입에 추가하였습니다.

Feat : 일기 작성시 답변 타입을 반환하도록 추가합니다. 

---

src/main/java/com/donkeys_today/server/DonkeyServerApplication.java
src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/application/reply/ReplyCreator.java
src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCreatedResponse.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/ReplyType.java
src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java

Hotfix : property source 추가 

---

src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
src/main/java/com/donkeys_today/server/support/exception/auth/SignUpException.java

- close #89 
Docs: 중복 회원가입 예외 처리

Docs: 중복 회원가입 예외 처리

---

src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
src/main/java/com/donkeys_today/server/support/exception/auth/SignInException.java

- close #93 
Docs: SignInException 생성

Docs: SignInException 생성

---

src/main/java/com/donkeys_today/server/application/diary/DiaryRetriever.java
src/main/java/com/donkeys_today/server/application/reply/ReplyRetriever.java
src/main/java/com/donkeys_today/server/application/user/UserAuthenticator.java
src/main/java/com/donkeys_today/server/application/user/UserRetriever.java
src/main/java/com/donkeys_today/server/application/user/UserService.java
src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java
src/main/java/com/donkeys_today/server/application/user/sterategy/SocialRegisterSterategy.java
src/main/java/com/donkeys_today/server/infrastructure/reply/ReplyRepository.java
src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
src/main/java/com/donkeys_today/server/support/exception/reply/ReplyException.java

- #98 
답장 관련 유저
답장 관련 중복 키, NotfoundException을 구현합니다.

Docs : 답변 중복 키 예외처리를 구현합니다. 

---

src/main/java/com/donkeys_today/server/application/auth/JwtProviderImpl.java
src/main/java/com/donkeys_today/server/application/user/UserService.java
src/main/java/com/donkeys_today/server/application/user/sterategy/KakaoAuthStrategy.java
src/main/java/com/donkeys_today/server/presentation/api/UserController.java
src/main/java/com/donkeys_today/server/presentation/user/UserControllerImpl.java
src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
src/main/java/com/donkeys_today/server/support/jwt/JwtProvider.java
src/main/java/com/donkeys_today/server/support/security/config/WhiteListConstants.java
src/main/java/com/donkeys_today/server/support/security/filter/JwtAuthenticationFilter.java

- close #95 
Fix: security white list 수정

Fix: security white list 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
src/main/java/com/donkeys_today/server/application/diary/DiaryService.java

- close #103 
Fix: 일기 삭제 및 조회 로직 수정

Fix: 일기 삭제 및 조회 로직 수정

---

src/main/java/com/donkeys_today/server/presentation/auth/AuthControllerImpl.java

Fix: 사소한 수정

---

src/main/java/com/donkeys_today/server/support/security/config/SecurityConfig.java

- close #111 
Refactor: cors 보안 삭제

Refactor: cors 보안 삭제

---

src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java
src/main/java/com/donkeys_today/server/presentation/reply/ReplyControllerImpl.java
src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
src/main/java/com/donkeys_today/server/support/exception/InvalidDateFormatException.java
src/main/java/com/donkeys_today/server/support/util/DateTimeValidator.java

- close #105 
날짜 관련 검증 로직을 추가합니다.

Docs : 날짜 검증 예외처리를 진행합니다. 

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/presentation/diary/DiaryControllerImpl.java

Fix : 일기 삭제 반환값 변경

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java

- close #118 
Fix: 일기 시간조회 오류 수정

Fix: 일기 시간조회 오류 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryCalenderGetResponse.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryListGetResponse.java

- close #120 
Fix: totalCloverCount 로직 수정

Fix: totalCloverCount 로직 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java

Fix : 정적 답변 생성 로직을 수정합니다. 

---

.github/workflows/cicd-pipeline.yml
src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/application/reply/ReplyCreator.java
src/main/java/com/donkeys_today/server/application/reply/ReplyService.java
src/main/java/com/donkeys_today/server/domain/reply/Reply.java
src/main/java/com/donkeys_today/server/support/config/ReplyProperty.java
src/main/java/com/donkeys_today/server/support/config/YamlPropertySourceFactory.java

Fix : 정적 답변 생성로직 변경

---

src/main/java/com/donkeys_today/server/application/diary/DiaryPolicy.java
src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/support/dto/type/ErrorType.java
src/main/java/com/donkeys_today/server/support/exception/DiaryExistException.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java

- close #127 
Fix: 일기 두번 작성 에러 수정

Fix: 일기 두번 작성 에러 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryFullInfo.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiaryResponse.java
src/main/java/com/donkeys_today/server/presentation/diary/dto/response/DiarySimpleInfo.java

- close #133 
일기를 삭제한적이 있다면 isDeleted 추가

Feat: 일기를 삭제한적이 있다면 응답에 isDeleted추가 

---

src/main/java/com/donkeys_today/server/application/user/sterategy/AppleAuthStrategy.java

- close #140 
Feat: 애플로그인 에러 메세지 수정

Feat: 애플로그인 에러 메세지 수정

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java

- close #151 
당일 일기 재작성 시 캘린더뷰 조회 diaryCount 미반영 수정

Feat: 당일 일기 재작성 시 캘린더뷰 조회 diaryCount 미반영 수정

---

.github/workflows/pr-test.yml
.gitignore
clody-domain/src/test/java/com/clody/domain/DomainApplicationTests.java
clody-infra/src/test/java/com/clody/infrastructure/InfrastructureInfraApplicationTests.java
clody-support/src/test/java/com/clody/support/SupportApplicationTests.java

-  #154 
PR 시 변경 모듈에 대한 테스트를 진행하도록 파이프라인 추가

Infra : 배포 이전 테스트 환경을 설정합니다. 

---

src/main/java/com/donkeys_today/server/application/diary/DiaryService.java
src/main/java/com/donkeys_today/server/application/user/UserRemover.java
src/main/java/com/donkeys_today/server/application/user/UserUpdater.java
src/main/java/com/donkeys_today/server/support/dto/type/SuccessType.java
src/main/java/com/donkeys_today/server/support/exception/GlobalExceptionAdvice.java
src/main/java/com/donkeys_today/server/support/exception/auth/UserDeleteException.java

Fix: 에러응답 추가

---

clody-app/src/main/java/com/clody/clodyapi/alarm/service/AlarmUpdateService.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignInRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignUpRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
clody-app/src/test/java/com/clody/clodyapi/user/service/UserApplicationServiceTest.java
clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmCommandService.java

- close #167
회원가입/로그인 마다 토큰갱신 로직 구현

Feat#167 : 회원가입/로그인 시 토큰 갱신을 구현합니다. 

---

clody-app/src/main/java/com/clody/clodyapi/user/controller/UserAuthControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignInRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignUpRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/mapper/UserMapper.java
clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
clody-domain/src/main/java/com/clody/domain/user/dto/UserDomainInfo.java
clody-domain/src/main/java/com/clody/domain/user/strategy/UserSocialInfo.java
clody-infra/src/main/java/com/clody/infra/models/user/strategy/AppleAuthStrategy.java
clody-infra/src/main/java/com/clody/infra/models/user/strategy/KakaoAuthStrategy.java

- close #171 
회원가입 및 로그인 코드 수정
안드는 회원가입시 email을 안보냅니다.
애플은 보냅니다.
애플로그인시 id_token 은 헤더에서 받습니다.

Refactor: 회원가입 및 로그인 코드 수정

---

clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryController.java
clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/diary/mapper/DiaryMapper.java
clody-app/src/main/java/com/clody/clodyapi/diary/service/DiaryRetrieverService.java
clody-app/src/main/java/com/clody/clodyapi/diary/service/UserDeletionService.java
clody-app/src/main/java/com/clody/clodyapi/diary/service/UserRetrieverService.java
clody-app/src/main/java/com/clody/clodyapi/diary/service/UserUpdateService.java
clody-app/src/main/java/com/clody/clodyapi/diary/usecase/DiaryRetrieverUsecase.java
clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserDeletionUsecase.java
clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserRetrieverUsecase.java
clody-app/src/main/java/com/clody/clodyapi/diary/usecase/UserUpdateUsecase.java
clody-app/src/main/java/com/clody/clodyapi/legacy/presentation/api/DiaryController.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/UserController.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/UserControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserNamePatchRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserDeleteResponse.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserInfoGetResponse.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserNamePatchResponse.java
clody-app/src/main/java/com/clody/clodyapi/user/mapper/UserMapper.java
clody-app/src/main/java/com/clody/clodyapi/user/service/UserApplicationService.java
clody-domain/src/main/java/com/clody/domain/diary/dto/UserDeletionInfo.java
clody-domain/src/main/java/com/clody/domain/diary/dto/response/DiaryListGetResponse.java
clody-domain/src/main/java/com/clody/domain/diary/dto/response/UserGetResponse.java
clody-domain/src/main/java/com/clody/domain/diary/service/UserCommandService.java
clody-domain/src/main/java/com/clody/domain/diary/service/UserQueryService.java
clody-domain/src/main/java/com/clody/domain/user/User.java
clody-domain/src/main/java/com/clody/domain/user/dto/UserInfo.java
clody-domain/src/main/java/com/clody/domain/user/service/UserAuthService.java

- close #166 
유저 정보 조회 및 수정 삭제 기능 구현

Feat: 유저 정보 조회 및 수정 삭제 기능 구현

---

clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryController.java
clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/diary/controller/dto/request/DiaryRequest.java
clody-domain/src/main/java/com/clody/domain/diary/service/DiaryQueryService.java

- close #174 
캘린더뷰 및 리스트뷰 일기 조회 리팩토링

Refactor: 캘린더뷰 및 리스트뷰 일기 조회 리팩토링

---

clody-app/src/main/java/com/clody/clodyapi/user/controller/UserAuthControllerImpl.java

Fix : 잘못된 어노테이션 제거

---

clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-domain/src/main/java/com/clody/domain/alarm/strategy/FirstAlarmDelayStrategy.java

Infra/#182 : 테스트 환경을 설정합니다. 

---

clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-domain/src/main/java/com/clody/domain/alarm/strategy/FirstAlarmDelayStrategy.java
clody-infra/src/main/java/com/clody/infra/models/reply/repository/ReplyRepositoryAdapter.java

-  #182 
트랜잭션 매니저를 변경하고, 명시합니다.

Infra/#182 : 트랜잭션 매니저 오류 해결

---

clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-domain/src/main/java/com/clody/domain/alarm/strategy/FirstAlarmDelayStrategy.java
clody-infra/src/main/java/com/clody/infra/models/diary/DiaryRepositoryAdapter.java
clody-infra/src/main/java/com/clody/infra/models/reply/repository/ReplyRepositoryAdapter.java

Infra/#182 : 삭제된 일기 조회 케이스 수정 

---

clody-app/src/main/java/com/clody/clodyapi/alarm/controller/AlarmControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/alarm/dto/response/AlarmFullResponse.java
clody-app/src/main/java/com/clody/clodyapi/alarm/dto/response/AlarmResponse.java
clody-app/src/main/java/com/clody/clodyapi/diary/controller/DiaryControllerImpl.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/request/UserSignUpRequest.java
clody-app/src/main/java/com/clody/clodyapi/user/controller/dto/response/UserInfoGetResponse.java
clody-domain/src/main/java/com/clody/domain/alarm/Alarm.java
clody-domain/src/main/java/com/clody/domain/alarm/service/AlarmCommandService.java
clody-domain/src/main/java/com/clody/domain/alarm/strategy/FirstAlarmDelayStrategy.java
clody-infra/src/main/java/com/clody/infra/models/alarm/AlarmRepositoryAdapter.java
clody-infra/src/main/java/com/clody/infra/models/diary/DiaryRepositoryAdapter.java
clody-infra/src/main/java/com/clody/infra/models/reply/repository/ReplyRepositoryAdapter.java

Fix/#182 : 알림 정보 변경을 수정합니다. 

---

clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
clody-domain/src/main/java/com/clody/domain/reply/service/processors/RodyMessageProcessor.java

FIx : LocalDateTime 파싱 오류 해결 

---

clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
clody-domain/src/main/java/com/clody/domain/reply/service/processors/RodyMessageProcessor.java
clody-infra/src/main/java/com/clody/infra/external/fcm/MessageContent.java

Fix/#197 : 푸시알림 메세지를 수정합니다. 

---

clody-domain/src/main/java/com/clody/domain/alarm/event/ReplyCompletionHandler.java
clody-domain/src/main/java/com/clody/domain/diary/service/DiaryCommandService.java
clody-domain/src/main/java/com/clody/domain/reply/service/processors/RodyMessageProcessor.java
clody-infra/src/main/java/com/clody/infra/external/fcm/MessageContent.java

- #197 
알림 설정 검증 과정에서 예외에 대응합니다.

Fix/#197 : 알림 설정 에러 대응 
